api_path = 'https://guitarclassification-production.up.railway.app'
signup_path = '/Auth/SignUp'
signin_path = '/Auth/SignIn'
checkauth_path = '/Auth/CheckAuthorized'
refresh_path = '/Auth/RefreshToken'
change_nickname_path = '/Profile/ChangeUsername'
change_email_path = '/Profile/ChangeEmail'
change_password_path = '/Profile/ChangePassword'
change_avatar_path = '/Profile/ChangeAvatar'
user_info_path = '/Profile/GetUserInfo'
tab_path = '/Tab'

blank_file = './blank.gp5'
tab_file = './tabs.gp5'